version: '3.4'

services:
  micromarket.services.rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - internal

  micromarket.services.apigateway:
    image: micromarket.services.apigateway
    build:
      context: .
      dockerfile: MicroMarket.Services.ApiGateway/Dockerfile
    environment:
      - RedisConnectionString=${REDIS_HOST_NAME}
    ports:
      - "8081:8081"
    depends_on:
      - shared.redis
    networks:
      - internal

  shared.redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - internal

  micromarket.services.identity:
    image: micromarket.services.identity
    build:
      context: .
      dockerfile: MicroMarket.Services.Identity/Dockerfile
    environment:
      - ConnectionString=Host=${IDENTITY_POSTGRES_HOST};Port=${IDENTITY_POSTGRES_PORT};Database=${IDENTITY_POSTGRES_DB};Username=${IDENTITY_POSTGRES_USER};Password=${IDENTITY_POSTGRES_PASSWORD}
      - RedisConnectionString=${REDIS_HOST_NAME}
    depends_on:
      - micromarket.services.identity.postgres
      - micromarket.services.rabbitmq
      - shared.redis
    networks:
      - internal

  micromarket.services.identity.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${IDENTITY_POSTGRES_DB}
      - POSTGRES_USER=${IDENTITY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${IDENTITY_POSTGRES_PASSWORD}
    networks:
      - internal

  micromarket.services.catalog:
    image: micromarket.services.catalog
    build:
      context: .
      dockerfile: MicroMarket.Services.Catalog/Dockerfile
    environment:
      - ConnectionString=Host=${CATALOG_POSTGRES_HOST};Port=${CATALOG_POSTGRES_PORT};Database=${CATALOG_POSTGRES_DB};Username=${CATALOG_POSTGRES_USER};Password=${CATALOG_POSTGRES_PASSWORD}
      - RabbitHost=${RABBIT_HOST}
    depends_on:
      - micromarket.services.catalog.postgres
      - micromarket.services.rabbitmq 
      - shared.redis
    networks:
      - internal

  micromarket.services.catalog.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${CATALOG_POSTGRES_DB}
      - POSTGRES_USER=${CATALOG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${CATALOG_POSTGRES_PASSWORD}
    networks:
      - internal

  micromarket.services.basket:
    image: micromarket.services.basket
    build:
      context: .
      dockerfile: MicroMarket.Services.Basket/Dockerfile
    environment:
      - ConnectionString=Host=${BASKET_POSTGRES_HOST};Port=${BASKET_POSTGRES_PORT};Database=${BASKET_POSTGRES_DB};Username=${BASKET_POSTGRES_USER};Password=${BASKET_POSTGRES_PASSWORD}
      - RabbitHost=${RABBIT_HOST}
    depends_on:
      - micromarket.services.basket.postgres
      - micromarket.services.rabbitmq 
      - shared.redis
    networks:
      - internal

  micromarket.services.basket.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${BASKET_POSTGRES_DB}
      - POSTGRES_USER=${BASKET_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BASKET_POSTGRES_PASSWORD}
    networks:
      - internal

  micromarket.services.ordering:
    image: micromarket.services.ordering
    build:
      context: .
      dockerfile: MicroMarket.Services.Ordering/Dockerfile
    environment:
      - ConnectionString=Host=${ORDERING_POSTGRES_HOST};Port=${ORDERING_POSTGRES_PORT};Database=${ORDERING_POSTGRES_DB};Username=${ORDERING_POSTGRES_USER};Password=${ORDERING_POSTGRES_PASSWORD}
      - RabbitHost=${RABBIT_HOST}
    depends_on:
      - micromarket.services.ordering.postgres
      - micromarket.services.rabbitmq
      - shared.redis
    networks:
      - internal

  micromarket.services.ordering.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${ORDERING_POSTGRES_DB}
      - POSTGRES_USER=${ORDERING_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDERING_POSTGRES_PASSWORD}
    networks:
      - internal

  micromarket.services.liqpay-payment:
    image: micromarket.services.liqpay-payment
    build:
      context: .
      dockerfile: MicroMarket.Services.LiqPayPayment/Dockerfile
    environment:
      - ConnectionString=Host=${LIQPAY_PAYMENT_POSTGRES_HOST};Port=${LIQPAY_PAYMENT_POSTGRES_PORT};Database=${LIQPAY_PAYMENT_POSTGRES_DB};Username=${LIQPAY_PAYMENT_POSTGRES_USER};Password=${LIQPAY_PAYMENT_POSTGRES_PASSWORD}
      - RabbitHost=${RABBIT_HOST}
    depends_on:
      - micromarket.services.liqpay-payment.postgres
      - micromarket.services.rabbitmq
      - shared.redis
    networks:
      - internal

  micromarket.services.liqpay-payment.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${LIQPAY_PAYMENT_POSTGRES_DB}
      - POSTGRES_USER=${LIQPAY_PAYMENT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${LIQPAY_PAYMENT_POSTGRES_PASSWORD}
    networks:
      - internal

networks:
  internal:
    driver: bridge




